- name: Deploy Minikube and Jenkins
  hosts: all
  gather_facts: yes

  tasks:
    - name: Update apt package index
      apt:
          update_cache: yes
          cache_valid_time: 3600
      become: yes

    - name: Install necessary packages
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
      become: yes

    - name: Add Docker's official GPG key
      ansible.builtin.shell:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      become: yes

    - name: Set up the Docker stable repository
      ansible.builtin.shell:
        cmd: echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: yes

    - name: Update apt package index (again)
      apt:
        update_cache: yes
      become: yes

    - name: Install the latest version of Docker CE
      apt:
        name: docker-ce
        state: latest
      become: yes

    - name: Ensure Docker service is enabled and running
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add Kubernetes signing key
      become: yes
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes repository
      become: yes
      ansible.builtin.apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install Kubernetes components
      become: yes
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Hold Kubernetes components at their current version
      become: yes
      command: apt-mark hold kubelet kubeadm kubectl




